### ISSUE TITLE
Install Script

### ISSUE THREAD

**Issue by tbordini** [DFIRKuiper/Kuiper#15]
**Describe the bug**
gunicorn do not start because don't have certificate files.
The install script do not create certificates for gunicorn

**Additional context**
In my enviroment i create manually the certificates

**Comment by salehmuhaysin** [comment]
hi, sorry for the delay,
it looks like the issue occured while uploading the new files to github, it updated the existing files but not uploading the files
I uploaded all the files now so it should be working

regarding generated new certificate, yes i recommend to use your own certificate in production environment
also download the other files, since there are many files not uploaded (currently fixed) that is required by Kuiper
