### ISSUE TITLE
SIGMA RULES

### ISSUE THREAD

**Issue by jmmalcala** [DFIRKuiper/Kuiper#17]
is there any way to upload sigma rules to KUIPER? 

Thank you

**Comment by salehmuhaysin** [comment]
hi,
Unfortunatly. no
the reason is that Sigma rules written based on different data sources and the fields names depends on them, so if you take the existing rules and want to apply it to Kuiper, the fields and data format will be different.

Note: you could write your Sigma rules based on Kuiper data format and fields, then use Sigma engine to convert the rules to elasticsearch query string, then add it as a rule in Kuiper (using "Simple Search" to write your elasticsearch query string).

**Comment by jmmalcala** [comment]
Thank you so much.

Congrats for Kuiper :-)
