### ISSUE TITLE
what content should be in .kjson?

### ISSUE THREAD

**Issue by w1th1c3** [DFIRKuiper/Kuiper#51]
i find many parser in kuiper is builtin ,such as **yum_sources**
![图片](https://user-images.githubusercontent.com/81949263/154879219-33446e58-0977-4050-b37f-86580183ca73.png)

i just dont understand how to create a  kjson file?,like yum_sources.kjson, what is the formate it should be?

i has try write this content to yum_sources.kjson
> {"baseurl":"www.xxxx.com/baseurl/xxxx"}

when upload to kuiper,and parse it
![图片](https://user-images.githubusercontent.com/81949263/154879486-7f2c8b95-7ede-4858-8e1a-1df8698421fc.png)
kjson parser has error,and dont tell me why?
the Artifacts view also has nothing :
![图片](https://user-images.githubusercontent.com/81949263/154879641-d9288c5f-da38-4825-9673-049d2094862d.png)

so , could you please write some wiki to tell us  how to create a *.kjson ,masure it can be parsed by kuiper and get a Artifacts result
i want to write some parser to parse some artifacts from linux machine,but your wiki is not easy to understand

**Comment by AbdulRhmanAlfaifi** [comment]
Hi,
`kjson` is a JSONL file (line separated JSON objects) with predefined fields. The following is an example with the data you provided:
```json
{
    "Data": {"baseurl":"www.xxxx.com/baseurl/xxxx"},
    "data_type": "<ARTIFACT_NAME>",
    "data_source": "<ARTIFACT_SOURCE>",
    "data_path": "<ARTIFACT_SOURCE_PATH>"
}
```
Where:
* <ARTIFACT_NAME> : is the same name as the parser name in Kuiper
* <ARTIFACT_SOURCE> : artifact source (ex. Firefox Browser History)
* <ARTIFACT_SOURCE_PATH>: Path to the artifact (ex. /home/u0041/.mozilla/firefox/XXXXXXXX.default/places.sqlite)

Also, make sure to add the field `@timestamp` to the JSON object in the field `Data` to be able to visualize it in the timeline otherwise it will default to `1700-01-01 00:00:00`

**Comment by w1th1c3** [comment]
@AbdulRhmanAlfaifi thx! it works, by the way, when kuiper will support get artifact from linux? i think ,linux is the same important as windows
