### ISSUE TITLE
Generate Timeline View csv when browsing artifacts

### ISSUE THREAD

**Issue by rvital-f** [DFIRKuiper/Kuiper#64]
Hello, 

Would it be possible to add the timeline export view when browsing artifacts on machines?

I like the timeline export with the views, but looking to get a workflow in where i get that but on an individual machine basis
<img width="229" alt="Screen Shot 2022-08-05 at 15 26 18" src="https://user-images.githubusercontent.com/110699325/183219251-b43c51f1-1fa8-4325-81a7-abe5a67b5194.png">
Want to be able to click the purple export button, but have it export the way the timeline export is. As it exports now it does not include much data
<img width="384" alt="Screen Shot 2022-08-05 at 15 28 38" src="https://user-images.githubusercontent.com/110699325/183219448-fe255698-3684-484f-85e2-e4bc51a5a0cd.png">
above is all it includes. Doesnt seem to use any of the Timeline Views

**Comment by salehmuhaysin** [comment]
hi,

yes it is possible to page the collected records from 'export' and pass it instead of this link in generating this timeline (https://github.com/DFIRKuiper/Kuiper/blob/8660f2eeaeab583de62166efea3803e56ce260ed/kuiper/app/controllers/case_management.py#L1428 but it need implementation 

regarding data from export, check this https://github.com/DFIRKuiper/Kuiper/issues/58
