### ISSUE TITLE
Edit Timeline Template?

### ISSUE THREAD

**Issue by rvital-f** [DFIRKuiper/Kuiper#66]
Hello,

Have a question with the Timeline/tag export sheet.

Whats the best way to customize it myself?

I found timeline.xlsx in /kuiper/app/utils/build_timeline and edited it in Libreoffice (when i edit in excel and send to kuiper, Kuiper throws error saying ZIP not found). I added a few columns to the template at timeline.xlsx. Then when i go to localhost:5000/case/caseID/timeline and download a new timeline, it does not use my template at all.

Any ideas?

Thanks

**Comment by salehmuhaysin** [comment]
hi,

im not sure what is the reason for `ZIP not found` if you could share the timeline template or the error message to help,

regarding the new columns, ensure that the all previous timeline for the case removed from `kuiper/kuiper/files/timeline/` before generating the timeline, becuase it will ignore the template timeline.xlsx and use the previous timelines

for the Timeline View, ensure it includes the following columns
- KuiperID
- Export_Version
- Export_Date
since it is used by Kuiper
