### ISSUE TITLE
Health page erroring out on fresh install

### ISSUE THREAD

**Issue by nyrm-f** [DFIRKuiper/Kuiper#75]
**Describe the bug**
Hello, have just ran a new install of Kuiper following the guide, noticed im getting an error with the health page now.

Maybe a new bug, or if I am doing something wrong pls lmk.

**To Reproduce**

1. Fresh install
2. run kuiper
3. go to health page
4. get below error
<img width="437" alt="Screen Shot 2022-10-17 at 2 31 19 PM" src="https://user-images.githubusercontent.com/110699325/196287830-0202a3c9-89eb-406a-abb7-d7f897523ae3.png">

**Comment by salehmuhaysin** [comment]
hi
I solved the issue, when i rebuilt the image, there was some kind of issue with Celery python3 did not worked ask before, not sure why, the problem was in the 
```python
from celery import Celery
```
in `celery_health.py` file. 
also i rebuilt the docker image, so you need to remove the old docker image and redownload it from dockerhub again.
also you need to pull the new modification from github

**Comment by nyrm-f** [comment]
thanks! checked and confirmed working now
